name:  buildtool
description:  A simple build system for Dart.
version: 0.0.1
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/buildtool

dependencies:
  args: any
  unittest: any
  #TODO: make dwc depend on buildtool
  web_components: any
